### ISSUE TITLE
unable to find check_design.py and markdown_to_html.r with singularity

### ISSUE THREAD

**Issue by aubinthomas** [nf-core/chipseq#102]
Hello,

I'm trying to use nf-core/chipseq through singularity, and with test profile I have a strange error : 

I'm using it with SLURM, with 

```
srun -c 16 --mem 128G sh runBatch.sh
```

my script file contains:
```bash
module load system/singularity-2.5.1
./nextflow run nf-core/chipseq -profile test,singularity -with-singularity work/singularity/nfcore-chipseq-1.0.0.img
```

The makeBWAindex, genome filter, get_software_versions are running well, but checkDesign and output_documentation are making errors : 
```
.command.sh: line 2: check_design.py: command not found
```
and
``` 
.command.sh: line 2: markdown_to_html.r: command not found
```

If I do a shell of the image I have the same issue. Nevertheless the other applications are running well since get_software_versions is OK.

- I have not bioconda and R installed.
- my `nextflow.config` contains : 

```nextflow
singularity {
  enabled = true
  autoMounts = true
  runOptions = "--bind /work/ChIPSeq"
}
```

Do you have any idea?

Thanks in advance,

aubin

**Comment by drpatelh** [comment]
Hi @aubinthomas . Apologies for the tardy response. Been on annual leave 🏖 

I have tried to run pipelines using `srun` in the past and observed some funny behaviour where multiple main Nextflow jobs were executed on the cluster. 

Can you try and run the command interactively after logging into a `screen` or `tmux` session?

e.g.
```
$ screen

$ module purge
$ module load system/singularity-2.5.1
$ ./nextflow run nf-core/chipseq -profile test
```

Note: you dont need to use `-profile test,singularity` because you are enabling it anyway in your custom config file.

You dont need to add the parameter below because Nextflow places the image there by default and so will find it anyway. If, however, you want the ability to re-use the image after conversion to Singularity to save time and processing then you can place it somewhere on your system and amend the path below appropriately.
`-with-singularity work/singularity/nfcore-chipseq-1.0.0.img`

You also need to tell Nextflow to use the `slurm` executor which you can do by adding in the lines below to `nextflow.config`:
https://github.com/nf-core/configs/blob/836da97efdd3b9be3a0715c57ae58ee5d85e3c98/conf/crick.config#L13-L16

You shouldnt need this line either:
`runOptions = "--bind /work/ChIPSeq"`

You wont need anything other than Nextflow and Singularity installed to run the pipeline because all of the software will be in the container. 

Can you try and re-run the pipeline interactively with the amendments above and let me know if it works?

**Comment by drpatelh** [comment]
Nextflow should append the pipeline `bin/` directory to `$PATH` so its a bit of a funny error. Which version of Nextflow are you using? May be worth updating that too if its an older version.

**Comment by aubinthomas** [comment]
So I did,
Thank you for the reply,
I have the current version of Nextflow 19.07.0
I modified my nextflow.config : 

```
singularity {
  enabled = true
  autoMounts = true
}
process{
  executor = 'slurm'
}
```


In a bash that I called with this command : 

```
$ srun -c 1 --mem 32G --pty --cpu-bind=no --mpi=none $SHELL
$ module purge
$ module load system/singularity-2.5.1
$ ./nextflow run nf-core/chipseq -profile test

```

The same error. The only new thing I have is on .command.err for get_software_versions that works since all outputs are created and good, despite none of the softwares are in the default path of the server:

> WARNING: Not mounting requested bind point (already mounted in container): /work/ChIPSeq/work/79/a096c8810f653cdca82f6d5a1f0298
> /opt/conda/envs/nf-core-chipseq-1.0.0/lib/python2.7/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   configs = yaml.load(f)
> /opt/conda/envs/nf-core-chipseq-1.0.0/lib/python2.7/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>   sp = yaml.load(f)
>

**Comment by drpatelh** [comment]
Ok. Can you send me the output of `ls -la ~/.nextflow/assets/nf-core/chipseq/bin/` please? That's where the pipeline is stored when downloaded via Nextflow. I'm wondering whether you have execute permissions on the scripts in that directory.

You could also try to delete that folder and run again to redownload the pipeline just to rule out issues with the download.

**Comment by aubinthomas** [comment]
```
$ ls -la ~/.nextflow/assets/nf-core/chipseq/bin/
total 83
drwxr-xr-x 2 taubin UMR9002  4096 17 sept. 16:55 .
drwxr-xr-x 8 taubin UMR9002  4096 17 sept. 16:55 ..
-rwxr-xr-x 1 taubin UMR9002  5761 17 sept. 16:55 bampe_rm_orphan.py
-rwxr-xr-x 1 taubin UMR9002  8703 17 sept. 16:55 check_design.py
-rwxr-xr-x 1 taubin UMR9002 13989 17 sept. 16:55 featurecounts_deseq2.r
-rwxr-xr-x 1 taubin UMR9002  3763 17 sept. 16:55 gtf2bed
-rwxr-xr-x 1 taubin UMR9002  5897 17 sept. 16:55 igv_files_to_session.py
-rwxr-xr-x 1 taubin UMR9002  8372 17 sept. 16:55 macs2_merged_expand.py
-rwxr-xr-x 1 taubin UMR9002  1124 17 sept. 16:55 markdown_to_html.r
-rwxr-xr-x 1 taubin UMR9002  7679 17 sept. 16:55 plot_homer_annotatepeaks.r
-rwxr-xr-x 1 taubin UMR9002  7016 17 sept. 16:55 plot_macs_qc.r
-rwxr-xr-x 1 taubin UMR9002  2218 17 sept. 16:55 plot_peak_intersect.r
-rwxr-xr-x 1 taubin UMR9002  2985 17 sept. 16:55 scrape_software_versions.py
```

**Comment by aubinthomas** [comment]
I deleted the entire directory, the same issue even if the brand new ~/.nextflow/assets/nf-core/chipseq/bin/ directory has been created

**Comment by aubinthomas** [comment]
OK, I solved my problem by adding in my nextflow.config

runOptions = '-B /work/$USER -B /home/$USER'
Very strange, this error occurs only on this cluster.

Thank you Harshil,

aubin

**Comment by shaniAmare** [comment]
Hi @aubinthomas and @drpatelh ,

Sorry for replying to a closed old thread. I am new to nexftlow and want to run the chips pipeline on `slurm`. I also get ransom python scripts (which are available in the `/assets/nf-core/chipseq/` dir.

I also added what was mentioned above - `runOptions = '-B /work/$USER -B /home/$USER' ` to my `ssets/nf-core/chipseq/nextflow.config` but still I get errors like below:

**Comment by shaniAmare** [comment]
OK to update I was able to successfully run the test data set by replacing the `~/.nextflow` symlink with the actual physical dir! 

But I know that is not sustainable as my `$HOME` is actually very low on storage. If you have any tips to make the symlink to ~/.nextflow work, I would be grateful!
