### ISSUE TITLE
BigWig Error:  sort: cannot create temporary file in '': Read-only file system

### ISSUE THREAD

**Issue by yjthu** [nf-core/chipseq#132]
Hi , the error is as follow:

Error executing process > 'BigWig (group1_R1)'

Caused by:
  Process `BigWig (group1_R1)` terminated with an error exit status (2)

Command executed:

  SCALE_FACTOR=$(grep 'mapped (' group1_R1.mLb.clN.sorted.bam.flagstat | awk '{print 1000000/$1}')
  echo $SCALE_FACTOR > group1_R1.mLb.clN.scale_factor.txt
  genomeCoverageBed -ibam group1_R1.mLb.clN.sorted.bam -bg -scale $SCALE_FACTOR -pc  | sort -k1,1 -k2,2n >  group1_R1.mLb.clN.bedGraph

  bedGraphToBigWig group1_R1.mLb.clN.bedGraph genome.fa.sizes group1_R1.mLb.clN.bigWig

  find * -type f -name "*.bigWig" -exec echo -e "bwa/mergedLibrary/bigwig/"{}"\t0,0,178" \; > group1_R1.mLb.clN.bigWig.igv.txt

Command exit status:
  2

Command output:
  (empty)

Command error:
  sort: cannot create temporary file in '': Read-only file system

**Comment by yjthu** [comment]
My command line is as follow:

nextflow run /mnt/data/PUBLIC/nf-core-pipe/nf-core-chipseq-1.1.0/workflow \
-with-singularity  /mnt/data/PUBLIC/nf-core-pipe/nf-core-chipseq-1.1.0/singularity-images/nf-core-chipseq-1.1.0.simg \
--fasta $testdatasets/reference/genome.fa \
--gtf $testdatasets/reference/genes.gtf \
--input design.csv \
--outdir /mnt/data/PUBLIC/nf-core-pipe/test-pipe/testChip/output

**Comment by yjthu** [comment]
Hi there,

this error have been fixed by add "-T '.' " after sort command in "main.nf".

sort -T '.' -k1,1 -k2,2n

**Comment by drpatelh** [comment]
Hi @yjthu ! Nice fix :smiley: This has come up before:
https://github.com/nf-core/chipseq/issues/123

and is probably because the `TMPDIR` environment variable isn't set on your system by default. There is a way to export this using a custom config file as outlined in the issue above or we can set it to the work directory for that process given that this is likely to be deleted after the pipeline has finished anyway.

Please feel free to submit a PR to the repo with a fix if you like :+1:

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/chipseq/pull/135

**Comment by brucemoran** [comment]
NB that while this is fixed, the release version is still 1.1.0 and so running `nextflow run nf-core/chipseq` still results in this issue.

**Comment by drpatelh** [comment]
Hi @brucemoran ! If you haven't already figured it out the easy fix until the next release would be to just export the variable below before you run the command for the pipeline:
`export TMPDIR=/tmp/`

**Comment by brucemoran** [comment]
Yes edited in the `-T .` solution, easier fix as my TMPDIR was defined, and mounted/bound in container. No idea why it didn't work, permissions all fine. One of those things I guess.

I thought releases would have been used to deal with issues like this, shows how little I know about the Github machine!

Thanks for a great pipeline, appreciate your reply and work.

**Comment by drpatelh** [comment]
Hmm, that is weird. That seems to have done the trick on all occasions except for this one! 

Yep, releases do normally incorporate bug fixes like this and other pipeline updates but the frequency with which you release depends quite heavily on having the time to do it all! :sweat_smile: That's why I tend to release less often but with bigger changes.

You're very welcome :+1:
