### ISSUE TITLE
plotHeatmap

### ISSUE THREAD

**Issue by ivokwee** [nf-core/chipseq#153]
Hi. In the deepTools module, it would be nice to include plotHeatmap inside the pipeline as the computeMatrix is already calculated. Thanks. Ivo

**Comment by drpatelh** [comment]
Hi @ivokwee I thought this may be a bit less useful because as it stands the heatmap would only be generated for a single IP (and maybe its corresponding IP). Given the `plotProfile` already gives you an idea as to the "average" enrichment at the TSS and it can be combined in MultiQC I thought that may be more useful?

**Comment by ivokwee** [comment]
Well having both is cool. Also the kmeans clustering heatmap is very nice. But if you want the pipeline to be "minimal but complete" then maybe let the user can do it afterwards manually.

**Comment by drpatelh** [comment]
Added this in here for you @ivokwee https://github.com/nf-core/chipseq/pull/158/commits/23cc6646edc7f6f1987a1f03a527286cce4e58a8 Thanks for the suggestion 👍
