### ISSUE TITLE
Annotation on DESeq2 results

### ISSUE THREAD

**Issue by dparrine** [nf-core/chipseq#196]
On the results of **DeSeq2**, the generated .txt files  _(the FDR0.05.results.txt, for example)_: why are the ranges not annotated? It would be convenient if the results were already annotated to genes – or even features, already.

**Comment by JoseEspinosa** [comment]
I think this issue could be closed since from version `2.0` the pipeline won't include anymore the differential analysis. This way it will fit the same idea as other nf-core pipelines e.g. `rnaseq` as this part needs a correct modeling of the experimental factors and to provide meaningful (and statistically correct) results.
It has been discussed in slack that with DLS2 the idea could be to create custom differential expression pipelines that are plugged as a downstream workflow after running in this case the chipseq pipeline.
