### ISSUE TITLE
Error in the json file created by the launcher?

### ISSUE THREAD

**Issue by hennion** [nf-core/chipseq#207]
When I create a json file with the launcher, it puts a string in  "fragment_size" :
```json
{
    "input": "design.csv",
    "single_end": "true",
    "fragment_size": "200",
    "seq_center": "Goe",
    "genome": "GRCm38",
    "save_reference": "true"
}
```
Which generates an error in BIGWIG:
```
Error executing process > 'BIGWIG (Neuron_K4me3_R1)'

Caused by:
  Cannot compare java.lang.String with value '200' and java.lang.Integer with value '0'
```
Replacing `"fragment_size": "200"` by `"fragment_size": 200`  solves the problem.  

This is minor, thanks for this great tool!

Magali

**Comment by JoseEspinosa** [comment]
Thanks for reporting! :smile: 
I just tested and it is fixed now. I will assume that was an error in nf-core tools when reading the type in the `nextflow_schema.json` since in the schema of the current stable release it is correctly assigned, see [here] (https://github.com/nf-core/chipseq/blob/6924b669422215f9021144b251e83fc9929be1fe/nextflow_schema.json#L26).
