### ISSUE TITLE
Chromosome "1" undefined in genome.fa.sizes

### ISSUE THREAD

**Issue by jianxinwang** [nf-core/chipseq#225]
Was successful to run this pipeline last up to sept 7. Now things are falling apart. With the same command line, I got "Chromome 10 undefined in genome.fa.sizes" error. Tried a few times same results. Today, I tried the this test command:

nextflow run nf-core/chipseq --genome GRCh37 -profile test,singularity

and Got Chromosome "1" undefined in genome.fa.sizes. Please investigate. Thanks

**Comment by JoseEspinosa** [comment]
Hi @jianxinwang 
Thanks for reporting. The `test` profile is used to assess that the pipeline is working properly with a small data set. For this reason, this data set contains a fasta and a gtf file with a single chromosome (see [here](https://github.com/nf-core/chipseq/blob/6ccf5fe9df93227cb093542cacc9729373a0665a/conf/test.config#L23-L24)). This annotation files are not compatible with the bed file downloaded from igenomes when the parameter genome is set to `GRCh37 `. To solve this issue, you could either not provide the genome in your command, i.e. `nextflow run nf-core/chipseq  -profile test,singularity` or if you want to run the tests with the `GRCh37` assembly you could try this command: `nextflow run nf-core/chipseq --genome GRCh37 --fasta s3://ngi-igenomes/igenomes/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa --gtf s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf -profile test,singularity --bwa_index false` that will overwrite the annotation files set on the test profile. However, the latter will take much longer and need more computational resources since the fasta file will correspond to the real genome and might not be the best option to run a test.

**Comment by JoseEspinosa** [comment]
Closed due to inactivity
