### ISSUE TITLE
Error in MERGED_BAM step

### ISSUE THREAD

**Issue by markdunning** [nf-core/chipseq#236]
Hi,

I am running the pipeline on public ChIP data, but getting stuck at the picard markduplicates step.

```
Error executing process > 'MERGED_BAM (H3K27me3_R2)'

Caused by:
  Process `MERGED_BAM (H3K27me3_R2)` terminated with an error exit status (140)

Command executed:

  picard -Xmx36g MarkDuplicates \
      INPUT=H3K27me3_R2_T1.Lb.sorted.bam \
      OUTPUT=H3K27me3_R2.mLb.mkD.sorted.bam \
      ASSUME_SORTED=true \
      REMOVE_DUPLICATES=false \
      METRICS_FILE=H3K27me3_R2.mLb.mkD.MarkDuplicates.metrics.txt \
      VALIDATION_STRINGENCY=LENIENT \
      TMP_DIR=tmp
  
  samtools index H3K27me3_R2.mLb.mkD.sorted.bam
  samtools idxstats H3K27me3_R2.mLb.mkD.sorted.bam > H3K27me3_R2.mLb.mkD.sorted.bam.idxstats
  samtools flagstat H3K27me3_R2.mLb.mkD.sorted.bam > H3K27me3_R2.mLb.mkD.sorted.bam.flagstat
  samtools stats H3K27me3_R2.mLb.mkD.sorted.bam > H3K27me3_R2.mLb.mkD.sorted.bam.stats

Command exit status:
  140

Command output:
  (empty)

Command error:
  /opt/conda/envs/nf-core-chipseq-1.2.2/bin/picard: line 5: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8): No such file or directory
  INFO	2021-11-24 02:55:51	MarkDuplicates	
```

The command I am using is:-

```
nextflow run nf-core/chipseq \
							-resume \
							--input chipseq_samplesheet.csv \
							--genome GRCh37	 \
							--outdir results_chipseq \
							-profile singularity \
							--max_memory 64.GB \
							--max_cpus 4
```

Thanks in advance for any advice

Regards,

**Comment by JoseEspinosa** [comment]
Hi @markdunning,
I guess you probably working with SGE batch scheduler in principle this error means you are using more resources than the ones requested, could be that you need more memory or time for this process. Since the process is labelled as `process_medium` it gets [these resources](https://github.com/nf-core/chipseq/blob/6924b669422215f9021144b251e83fc9929be1fe/conf/base.config#L28-L32) by default.
You can create a custom `my.config` file and increase them e.g.:

```
withName: MERGED_BAM {
    memory =  100.GB
    time =  20.h
  }
```
And then update your command adding `-c my.config` to it.
You will also need to increase your command to increase the available resources accordingly, or maybe it will also work just increasing your max memory to 72 Gb, so that if the process fails it is run again with twice the memory. Se also the code I linked above.

Hope this helps!

**Comment by markdunning** [comment]
Thanks! I increased the memory allocation and it does indeed work now.
