### ISSUE TITLE
Test fails on GCP

### ISSUE THREAD

**Issue by hnawar** [nf-core/chipseq#274]
The pipeline fails when running with GCP Life Sciences Executor at the steps below. 
- NFCORE_CHIPSEQ:CHIPSEQ:PRESEQ_LCEXTRAP 
- NFCORE_CHIPSEQ:CHIPSEQ:MULTIQC_CUSTOM_PEAKS

Based on the command.log I suspect it is a container user related issue similar to issue reported earlier for rna-seq
<<command.log>>
+ cd /wd/07/58802da4e48688a80a1815d6014f3e
+ gsutil -m -q cp gs://bucket-name/wd/07/58802da4e48688a80a1815d6014f3e/.command.run .
+ bash .command.run nxf_stage
+ [[ 1 -gt 0 ]]
+ ls -lah /wd/07/58802da4e48688a80a1815d6014f3e
total 120K
drwxr-xr-x 4 root root 4.0K May  4 11:39 .
drwxr-xr-x 3 root root 4.0K May  4 11:39 ..
-rw-r--r-- 1 root root  228 May  4 11:39 .command.log
-rw-r--r-- 1 root root  13K May  4 11:39 .command.run
-rw-r--r-- 1 root root  430 May  4 11:39 .command.sh
-rw-r--r-- 1 root root   46 May  4 11:39 SPT5_T15_REP1.FRiP.txt
-rw-r--r-- 1 root root  54K May  4 11:39 SPT5_T15_REP1_peaks.broadPeak
-rw-r--r-- 1 root root  523 May  4 11:39 frip_score_header.txt
drwx------ 2 root root  16K May  4 11:38 lost+found
drwxr-xr-x 2 root root 4.0K May  4 11:39 nextflow-bin
-rw-r--r-- 1 root root  317 May  4 11:39 peak_count_header.txt
+ cd /wd/07/58802da4e48688a80a1815d6014f3e
+ bash .command.run nxf_unstage
CommandException: No URLs matched: .command.out
CommandException: 1 file/object could not be transferred.
CommandException: No URLs matched: .command.err
CommandException: 1 file/object could not be transferred.
CommandException: No URLs matched: .command.trace
CommandException: 1 file/object could not be transferred.
CommandException: No URLs matched: .exitcode
CommandException: 1 file/object could not be transferred.
ls: cannot access '*.peak_count_mqc.tsv': No such file or directory
ls: cannot access '*.FRiP_mqc.tsv': No such file or directory

<<end of command.log>>

Name: NFCORE_CHIPSEQ:CHIPSEQ:PRESEQ_LCEXTRAP 

Command

preseq \
    lc_extrap \
    -verbose -bam -seed 1 \
    -pe \
    -output SPT5_T15_REP2.mLb.clN.lc_extrap.txt \
    SPT5_T15_REP2.mLb.clN.sorted.bam
cp .command.err SPT5_T15_REP2.mLb.clN.command.log

cat <<-END_VERSIONS > versions.yml
"NFCORE_CHIPSEQ:CHIPSEQ:PRESEQ_LCEXTRAP":
    preseq: $(echo $(preseq 2>&1) | sed 's/^.*Version: //; s/Usage:.*$//')
END_VERSIONS
Status
Exit: 1 (FAILED) Attempts: 1 (action: IGNORE)

and 

Name: NFCORE_CHIPSEQ:CHIPSEQ:MULTIQC_CUSTOM_PEAKS
[Execution log](https://tower.nf/#taskExecutionLogTabPane)
Command

cat SPT5_T15_REP1_peaks.broadPeak | wc -l | awk -v OFS='	' '{ print "SPT5_T15_REP1", $1 }' | cat peak_count_header.txt - > SPT5_T15_REP1.peak_count_mqc.tsv
cat frip_score_header.txt SPT5_T15_REP1.FRiP.txt > SPT5_T15_REP1.FRiP_mqc.tsv

cat <<-END_VERSIONS > versions.yml
"NFCORE_CHIPSEQ:CHIPSEQ:MULTIQC_CUSTOM_PEAKS":
    sed: $(echo $(sed --version 2>&1) | sed 's/^.*GNU sed) //; s/ .*$//')
END_VERSIONS
Status
Exit: 9 (FAILED) Attempts: 1 (action: FINISH)

**Comment by drpatelh** [comment]
Hi @hnawar ! Did you try the `-r dev` branch of the pipeline because @JoseEspinosa has replaced the problematic containers we found in rnaseq already. This pipeline is edging closer to a stable release so be good to verify it works on GCP beforehand.

**Comment by drpatelh** [comment]
Ok. The PRESEQ error is due to the nature of the test data being too sparse and is expected. It can be quite flaky at times so I set the process up to be ignored on error. The same error is also observed in the Github Actions for the pipeline [here](https://github.com/nf-core/chipseq/runs/6271936787?check_suite_focus=true) so it isn't something specific to GCP.
 
The second one is due to a bug because this container was probably forgotten to be replaced [here](https://github.com/nf-core/chipseq/blob/420bcb7b37fbf5ec3487a3f8ff8252b28756be71/modules/local/multiqc_custom_peaks.nf#L3-L6). Let me do that quickly now.

**Comment by drpatelh** [comment]
This should be good to go now @hnawar ! 

Fixed in https://github.com/nf-core/chipseq/pull/275. As I mentioned, the PRESEQ error is expected but I created a separate issue to track that in https://github.com/nf-core/chipseq/issues/276

If you are triggering from local then please run the following command beforehand to pull in the latest changes:

```
nextflow pull nf-core/chipseq-r dev
```

Let us know how it goes!

**Comment by hnawar** [comment]
Thanks @drpatelh this now runs smoothly with the exception of PRESEQ as you mentioned. PRESEQ exits with the floowing error 
ERROR:	max count before zero is less than min required count (4) duplicates removed

But as you mentioned this is to be expected.

Thanks for the amazing and quick response.

**Comment by drpatelh** [comment]
You are welcome @hnawar ! Thanks for reporting!
