### ISSUE TITLE
Macs2 Output 

### ISSUE THREAD

**Issue by kittyBS** [nf-core/chipseq#388]
### Description of the bug

Hello,
I am aware that there is an open issue (#336) regarding this matter, but I still wanted to update the problem. Despite trying the codes below, I am unable to obtain the outputs from MACS2. Additionally, using the -genome parameter results in the following error: 'taging foreign file: s3://ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/Bowtie2Index ERROR ~ Error executing process > 'NFCORE_CHIPSEQ:CHIPSEQ:ALIGN_BOWTIE2:BOWTIE2_ALIGN (1)' Caused by: Not a valid S3 file system provider file attribute view: java.nio.file.attribute.BasicWithKeyFileAttributeView -- Check '.nextflow.log' file for details -[nf-core/chipseq] Pipeline completed with errors- WARN: Killing running tasks (1)'. Can you help me with this?
Best regards

### Command used and terminal output

```console
nextflow run nf-core/chipseq --input samplesheet.csv --genome GRCh38 --aligner bowtie2 --outdir chipseq --fasta GRCh38.primary_assembly.genome.fa.gz --gtf gencode.v38.primary_assembly.annotation.gtf.gz --macs_gsize 2913022398 --broad --save_maca_pileup -profile docker

nextflow run nf-core/chipseq --input 
samplesheet.csv --aligner bowtie2 --outdir /
chipseq --fasta GRCh38.primary_assembly.genome.fa.gz --gtf gencode.v38.primary_assembly.annotation.gtf.gz --macs_gsize 2913022398 -profile docker
```

### System information

Version of nf-core/chipseq 2.0.0
Hardware HPC
Executor slurm

**Comment by JoseEspinosa** [comment]
See the answer [here](https://github.com/nf-core/chipseq/issues/336#issuecomment-2245159628) regarding the macs issue.
Concerning the aws download problem, you can bypass the issue by manually downloading the [iGenomes reference file](https://ewels.github.io/AWS-iGenomes/) and providing it to the pipeline using the `--bowtie2_index` parameter.
If you don't want to pre-download the file, from slacks exchanges this error is many times caused due to not be using a suitable java version, so you can also try to update java (Nextflow needs java 11 or later)

**Comment by JoseEspinosa** [comment]
I will close this issue now for lack of activity, if you have any further questions please feel free to re-open it.
