### ISSUE TITLE
BWA can't find bwa index or fasta file

### ISSUE THREAD

**Issue by ge2sasag** [nf-core/chipseq#65]
Hi,

I'm trying to run the chipseq pipeline in a personal computer. The pipeline is running ok until it reaches BWA aligning step. I get this error:

```
[Caused by:
  Process `bwa (H3K27ac_DMSO)` terminated with an error exit status (1)
Command executed:
  bwa mem -M hg19/genome.fa H3K27ac_DMSO_trimmed.fq.gz | samtools view -bT hg19 - | samtools view -b -q 1 -F 4 -F 256 > H3K27ac_DMSO.bam
Command exit status:
  1
Command output:
  (empty)
Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  [E::bwa_idx_load_from_disk] fail to locate the index files
  [samfaipath] build FASTA index...
  [E::fai_build3] Failed to open the FASTA file hg19
  [samfaipath] fail to build FASTA index.
```

This is my code:

```bash
nextflow run nf-core/chipseq \
    -profile standard,docker \
    --max_memory '30.GB' \
    --singleEnd \
    --bwa_index '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/hg19/' \
    --blacklist_filtering \
    --blacklist '/home/gema/.nextflow/assets/nf-core/chipseq/blacklists' \
    --genome GRCh37 \
    --reads '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/*.fastq' \
    --macsconfig '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/macssetup.config'
```

I also added this to the nextflow.config file:

```groovy
genomes {
    'GRCh37' {
        bwa = '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/hg19'
        fasta = '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/hg19/GRCh37.fa' // used if bwa index not given
    }
    // Any number of additional genomes, key is used with --genome
  }
}
```

Why BWA is running `bwa mem -M hg19/genome.fa` if I indicated the pathway to the file everywhere?

Thank you very much in advance

Best
Gema

**Comment by drpatelh** [comment]
Hi Gemma,

The simplest answer is that the name of the fasta file is hardcoded as being `genome.fa` which means that if your local fasta file has a different name then it wont be found. 
You can see this here:
https://github.com/nf-core/chipseq/blob/5f67d82e330c33eb2186c3210043ddbb17d8b5f2/main.nf#L400

It was implemented in this way because all of the iGenomes fasta files are called `genome.fa`. Having said that the code does need to be updated to be more flexible to custom file names.

If you dont have a pressing need to use your local version of the genome the easiest fix would be to let the pipeline download all of the required files from iGenomes, and to generate the BWA index for you. 

This command should do it:
`nextflow run nf-core/chipseq -profile standard,docker --max_memory '30.GB' --singleEnd --blacklist_filtering --saveReference --genome GRCh37 --reads '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/*.fastq' --macsconfig '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/macssetup.config'`

The `--saveReference` parameter will save the BWA index in `results/BWAIndex/`, and then you should be able to use the command below for future runs if you want to avoid regenerating the index:
`nextflow run nf-core/chipseq -profile standard,docker --max_memory '30.GB' --singleEnd --blacklist_filtering --saveReference --genome GRCh37 --reads '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/*.fastq' --macsconfig '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/macssetup.config' --bwa_index <PATH_TO>/results/BWAIndex/`

**Comment by ge2sasag** [comment]
Thank you very much for your fast answer! I'm running it now and we will see if it works

**Comment by ewels** [comment]
Yes, we should update how this works. The reason we don't give the full path to the fasta file is because we need to use the directory as the filepath so that we get _all_ of the files it contains (not just the fasta file). But it's bad that the `genome.fa` name is hardcoded.

I guess we'll need an additional `params` variable here. eg. `--bwa_index_basename` or something. Unless anyone has a better idea.

We could perhaps take the full path to the fasta file and then split it into basename and directory to populate these two variables? Then it would still be a single parameter to specify.

**Comment by drpatelh** [comment]
Yep. Ive implemented it in this way for the `atacseq` pipeline, and it should deal with such issues:
https://github.com/nf-core/atacseq/blob/a054df30932d1283ab2565381e73e88f37fce070/main.nf#L595

**Comment by ewels** [comment]
Nice! What do you think about doing it as a single path and splitting it into two variables?

**Comment by drpatelh** [comment]
Hmmm. So do you mean changing this line:
https://github.com/nf-core/atacseq/blob/a054df30932d1283ab2565381e73e88f37fce070/conf/igenomes.config#L14

to `fasta = "${params.igenomes_base}/Homo_sapiens/Ensembl/GRCh37/Sequence/BWAIndex/genome.fa"`

If so, that would mean that the fasta file would have to be located in the same folder as the bwa index. This will work for the iGenomes setup but if `--fasta` is specified as a custom parameter then it may not always be the case.

**Comment by drpatelh** [comment]
Or do you mean changing:
https://github.com/nf-core/atacseq/blob/a054df30932d1283ab2565381e73e88f37fce070/conf/igenomes.config#L15

to 
`bwa = "${params.igenomes_base}/Homo_sapiens/Ensembl/GRCh37/Sequence/BWAIndex/genome.fa"`

I guess that could work.

**Comment by ewels** [comment]
The second, but using groovy to split this in to two variables so that we still have the same channel and basename that we currently have, but both generated from a single `params` command line option.

**Comment by drpatelh** [comment]
How about this? 
```
if( params.bwa_index ){
    lastPath = params.bwa_index.lastIndexOf(File.separator)
    bwa_dir =  params.bwa_index.substring(0,lastPath+1)
    bwa_base = params.bwa_index.substring(lastPath+1)

    bwa_index = Channel
        .fromPath(bwa_dir)
        .ifEmpty { exit 1, "BWA index not found: ${params.bwa_index}" }
} else if ( params.fasta ){
    fasta = file(params.fasta)
    if( !fasta.exists() ) exit 1, "Fasta file not found: ${params.fasta}"
} else {
    exit 1, "No reference genome specified!"
}
```

Most Groovy way I could find. Should be platform independent too.

**Comment by ewels** [comment]
Yes, exactly! And then use `$bwa_base` in the process. Note that these variables will also have to be set when building the pipeline. Looks great 👍

**Comment by drpatelh** [comment]
Cool. How do you mean that they will have to be set?

Ive just realised `bwa_base` will also need to be worked out from `fasta` if `bwa_index` isnt specified. Made the edits above.

**Comment by ewels** [comment]
I meant basically what you just did above 👍

**Comment by ge2sasag** [comment]
Hi again, I run the analysis with the command indicated by @drpatelh 

`nextflow run nf-core/chipseq \
    -profile standard,docker \
    --max_memory '30.GB' \
    --singleEnd \
    --blacklist_filtering \
    --saveReference \
    --genome GRCh37 \
    --reads '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/*.fastq' \
    --macsconfig '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/macssetup.config'`

but I got the same error, It can not find the bwa index or fasta file. I'm not sure if it can dowload the genome automatically from iGenomes. I'm running the pipeline from my own computer, not from UPPMAX.

**Comment by drpatelh** [comment]
@ge2sasag I wonder if its because the pipeline is still picking up the custom `nextflow.config` file you created. Can you delete/relocate that from the folder you are running the pipeline. 

It may also be worth running `rm -rf .nextflow* results/ work/` just in case you have remnants from the last run of the pipeline.

Would be great if you could join the `chipseq` channel on [Slack](https://nf-core-invite.herokuapp.com/)! Will be easier to debug things there.

**Comment by ge2sasag** [comment]
Ok I'm joining! 

I deleted everything and reinstaled nf-core to have the original files. Now I get this error:

```
(base) gema@Gema-Desktop:/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/test$ nextflow run nf-core/chipseq -profile standard,docker --max_memory '30.GB' --singleEnd --blacklist_filtering --blacklist '/home/gema/.nextflow/assets/nf-core/chipseq/blacklists' --genome GRCh37 --reads '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/test/*.fastq' --macsconfig '/media/gema/1C2AD20F2AD1E5B4/NGS_analysis/GSE58740/FASTQ_files/chip-seq/macssetup.config'
```
```
N E X T F L O W  ~  version 19.01.0
Launching `nf-core/chipseq` [sad_fermi] - revision: 5f67d82e33 [master]
ERROR ~ No such variable: GRCh37
 -- Check script 'main.nf' at line: 104 or see '.nextflow.log' file for more details
```

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/chipseq/pull/66
