### ISSUE TITLE
nf-core/chipseq blacklist error

### ISSUE THREAD

**Issue by mglgc** [nf-core/chipseq#98]
Hi all,
The pipeline runned with "--genome GRCh37" (or GRCh38) and "-profile docker" options exits showing the error messsage "The requested file (.../GRCh37-blacklist.bed) could not be opened. Error message: (No such file or directory). Exiting!". If using --blacklist option with a custom right path the same error arises. Of course, paths and blacklist bed file format have been checked right.
Anyone could help or point to a fix? Thanks a lot in advance.

**Comment by drpatelh** [comment]
Hi @mglgc . A similar issue propped up with the `atacseq` pipeline yesterday.
https://github.com/nf-core/atacseq/issues/39

`Error message: (No such file or directory). Exiting!` generally means its a file permission issue.

Can you send me the command you are using? and check if the blacklist file exists in the pulled version of the pipeline?
`ls ~/.nextflow/assets/nf-core/chipseq/assets/blacklists/GRCh37-blacklist.bed`

**Comment by mglgc** [comment]
Hi drpatelh,
Thanks for your reply.
I don't think about any permission issue as I've just said I've alternatively used the --blacklist option with my own path and blacklist file. Anyway, yo'll find below the relevant command options I'm using:

nextflow run nf-core/chipseq --genome GRCh37 --aligner hisat2 --singleEnd -profile docker

Best!

**Comment by drpatelh** [comment]
Ok. So `--aligner hisat2` is definitely not an option for the `chipseq` pipeline because it only uses `bwa mem`. Thats from the `rnaseq` pipeline! Shouldnt be the cause of the error though...

You also need to give the pipeline a `design.csv` which is a mandatory argument:
https://github.com/nf-core/chipseq/blob/master/docs/usage.md#running-the-pipeline

Can you join the `chipseq` channel on the `nf-core` Slack workspace and we can debug further if required.
https://nf-core-invite.herokuapp.com/

**Comment by mglgc** [comment]
Dear drpatelh,
Of course I have a design.csv. Bear in mind that I have only one error, that related to the blacklist not found file. Regarding the hisat2 aligner, I have used it in several chipseq pipeline runnings with no problem.
I'll join by Slack to report the error. Thanks.
